name: 'eip-3074-tools'
description: "Patched versions of foundry's forge and solc to be used with EIP-3074 contracts"
inputs:
  foundry-command:
    description: 'The foundry command to execute'
    required: true
    default: build
  foundry-directory:
    description: 'The root directory of your foundry project'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.foundry-command }}
    - --use
    - /usr/local/bin/solc
    - --root
    - ${{ inputs.foundry-directory }}
