name: 'eip-3074-tools'
description: "Patched versions of foundry's forge and solc to be used with EIP-3074 contracts"
inputs:
  foundry-command:
    description: 'The foundry command to execute'
    required: true
    default: build
  foundry-directory:
    description: 'The root directory of your foundry project'
    required: true
  foundry-script:
    description: 'The path to the forge script to execute'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --foundry-command
    - ${{ inputs.foundry-command }}
    - --foundry-directory
    - ${{ inputs.foundry-directory }}
    - --foundry-script
    - ${{ inputs.foundry-script }}
